// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// Budget Types
export const GET_BUDGETS = 'GET_BUDGETS';
export const BUDGET_ERROR = 'BUDGET_ERROR';
export const ADD_BUDGET = 'ADD_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';

// Transaction Types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

// Notification Types
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const MARK_AS_READ = 'MARK_AS_READ';
export const UPDATE_NOTIFICATION_PREFERENCES = 'UPDATE_NOTIFICATION_PREFERENCES';

// Goal Types
export const GET_GOALS = 'GET_GOALS';
export const GOAL_ERROR = 'GOAL_ERROR';
export const ADD_GOAL = 'ADD_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const UPDATE_GOAL = 'UPDATE_GOAL';
export const UPDATE_GOAL_PROGRESS = 'UPDATE_GOAL_PROGRESS';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT'; 

//Review Types
// export const POST_REVIEW = 'POST_REVIEW';
// export const UPDATE_REVIEW = 'UPDATE_REVIEW';
// export const DELETE_REVIEW = 'DELETE_REVIEW';
// export const REVIEW_ERROR = 'REVIEW_ERROR';

// export const GET_REVIEW = 'GET_REVIEW_REQUEST';
// export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
// export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE';

// export const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';
// export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
// export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

// export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
// export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
// export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

// export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
// export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
// export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";