// // Auth Action Types
// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// export const LOGOUT = 'LOGOUT';
// export const REGISTER_REQUEST = 'REGISTER_REQUEST';
// export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// // User Action Types
// export const GET_USER_PROFILE = 'GET_USER_PROFILE';
// export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
// export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';

// // Transaction Action Types
// export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
// export const ADD_TRANSACTION = 'ADD_TRANSACTION';
// export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
// export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
// export const GET_TRANSACTION_STATISTICS = 'GET_TRANSACTION_STATISTICS';

// // Budget Action Types
// export const GET_BUDGETS = 'GET_BUDGETS';
// export const ADD_BUDGET = 'ADD_BUDGET';
// export const UPDATE_BUDGET = 'UPDATE_BUDGET';
// export const DELETE_BUDGET = 'DELETE_BUDGET';
// export const GET_BUDGET_STATISTICS = 'GET_BUDGET_STATISTICS';

// // Goal Action Types
// export const GET_GOALS = 'GET_GOALS';
// export const ADD_GOAL = 'ADD_GOAL';
// export const UPDATE_GOAL = 'UPDATE_GOAL';
// export const DELETE_GOAL = 'DELETE_GOAL';
// export const UPDATE_GOAL_PROGRESS = 'UPDATE_GOAL_PROGRESS';

// // Report Action Types
// export const GET_INCOME_REPORT = 'GET_INCOME_REPORT';
// export const GET_EXPENSE_REPORT = 'GET_EXPENSE_REPORT';
// export const GET_FINANCIAL_SUMMARY = 'GET_FINANCIAL_SUMMARY';
// export const EXPORT_REPORTS = 'EXPORT_REPORTS';

// // Notification Action Types
// export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
// export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
// export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
// export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
// export const CLEAR_READ_NOTIFICATIONS = 'CLEAR_READ_NOTIFICATIONS';
// export const UPDATE_NOTIFICATION_PREFERENCES = 'UPDATE_NOTIFICATION_PREFERENCES';
// export const GET_NOTIFICATION_PREFERENCES = 'GET_NOTIFICATION_PREFERENCES';

// // UI Action Types
// export const SET_LOADING = 'SET_LOADING';
// export const SET_ERROR = 'SET_ERROR';
// export const CLEAR_ERROR = 'CLEAR_ERROR';
// export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
// export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';

// // Filter Action Types
// export const SET_DATE_FILTER = 'SET_DATE_FILTER';
// export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
// export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
// export const CLEAR_FILTERS = 'CLEAR_FILTERS';

// Auth Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// User Action Types
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';

// Transaction Action Types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTION_STATISTICS = 'GET_TRANSACTION_STATISTICS';

// Budget Action Types
export const GET_BUDGETS = 'GET_BUDGETS';
export const ADD_BUDGET = 'ADD_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const GET_BUDGET_STATISTICS = 'GET_BUDGET_STATISTICS';

// Goal Action Types
export const GET_GOALS = 'GET_GOALS';
export const ADD_GOAL = 'ADD_GOAL';
export const UPDATE_GOAL = 'UPDATE_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const UPDATE_GOAL_PROGRESS = 'UPDATE_GOAL_PROGRESS';

// Review Action Types
export const GET_REVIEWS = 'GET_REVIEWS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UPDATE_REVIEW_VOTES = 'UPDATE_REVIEW_VOTES';

// Report Action Types
export const GET_INCOME_REPORT = 'GET_INCOME_REPORT';
export const GET_EXPENSE_REPORT = 'GET_EXPENSE_REPORT';
export const GET_FINANCIAL_SUMMARY = 'GET_FINANCIAL_SUMMARY';
export const EXPORT_REPORTS = 'EXPORT_REPORTS';

// Notification Action Types
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const CLEAR_READ_NOTIFICATIONS = 'CLEAR_READ_NOTIFICATIONS';
export const UPDATE_NOTIFICATION_PREFERENCES = 'UPDATE_NOTIFICATION_PREFERENCES';
export const GET_NOTIFICATION_PREFERENCES = 'GET_NOTIFICATION_PREFERENCES';

// UI Action Types
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE';

// Filter Action Types
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';